"""Export a demo snapshot of the heat pipeline for the web app's offline mode.

Run:  python -m app.tools.export_demo_snapshot

Writes web/public/demo/*.json produced by the SAME HeatPredictionService that
powers the live API — a static render of the real pipeline (section 17 demo
resilience), never hand-authored values. The web app prefers the live API and
falls back to this snapshot, labelling it "OFFLINE SNAPSHOT".
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from app.config import REPO_ROOT
from app.data.generate_static_data import DISTRICT_BBOXES, DISTRICT_META
from app.core.types import HeatModelParameters
from app.engines.heat.engine import HeatPredictionService
from app.providers.cooling import CoolingSpotProvider
from app.providers.spatial import SpatialData
from app.providers.weather import MockWeatherProvider
from app.services.heatmap import HeatMapService

OUT_DIR = REPO_ROOT / "web" / "public" / "demo"
TS_OUT = REPO_ROOT / "web" / "src" / "features" / "heatmap" / "demoSnapshots.ts"
GAZETTEER_TS_OUT = REPO_ROOT / "web" / "src" / "features" / "heatmap" / "gazetteer.ts"
DISTRICTS_TS_OUT = REPO_ROOT / "web" / "src" / "features" / "heatmap" / "districts.ts"
# Embedded offline snapshots cover the flagship demo districts (keeps the
# single-file bundle ~13 MB). All 19 districts are available via the live
# backend; the UI labels this honestly in offline mode.
DISTRICTS = ["central-western", "kowloon-yau-tsim", "northern-metropolis"]
HOURS = [6, 9, 12, 15, 18, 21]
DATE = datetime(2026, 6, 21)  # fixed demo date (summer solstice)


def main() -> None:
    spatial = SpatialData()
    heat = HeatPredictionService(spatial, MockWeatherProvider(), HeatModelParameters())
    service = HeatMapService(spatial, heat)
    cooling = CoolingSpotProvider(spatial)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    snapshots: dict[str, object] = {}

    for district in DISTRICTS:
        for hour in HOURS:
            # subdivisions=2: 2x2 sub-cells per land-use cell (~75 m spacing)
            # so the web heatmap kernel merges into a CONTINUOUS field instead
            # of discrete per-cell blobs. Same HeatPredictionService per point.
            layer = service.build(
                district, datetime(DATE.year, DATE.month, DATE.day, hour),
                subdivisions=2,
            )
            snapshots[f"{district}|{hour}"] = layer
            path = OUT_DIR / f"heatmap_{district}_{hour:02d}.json"
            path.write_text(json.dumps(layer, separators=(",", ":")), encoding="utf-8")
            print(f"wrote {path.name}: {len(layer['cells'])} cells")

        spots = cooling.list(district)
        snapshots[f"{district}|cooling"] = spots
        spots_path = OUT_DIR / f"cooling_{district}.json"
        spots_path.write_text(
            json.dumps(spots, separators=(",", ":")),
            encoding="utf-8",
        )
        print(f"wrote {spots_path.name}")

    # Embedded snapshot module: lets the single-file build carry the whole
    # offline demo inside one HTML (no server, no fetches).
    ts = (
        "/* AUTO-GENERATED by app.tools.export_demo_snapshot - do not edit. */\n"
        "/* Static render of the real HeatPredictionService pipeline. */\n"
        "export const SNAPSHOTS: Record<string, unknown> = "
        + json.dumps(snapshots, separators=(",", ":"))
        + ";\n"
    )
    TS_OUT.write_text(ts, encoding="utf-8")
    print(f"wrote {TS_OUT.name} ({len(snapshots)} entries)")

    # Gazetteer module for offline place search (generated from the backend
    # source of truth so there is exactly one catalogue).
    from app.providers.gazetteer import _GAZETTEER  # noqa: PLC0415

    places = [
        {
            "id": f"geo-{d}-{n.lower().replace(' ', '-')[:24]}",
            "name": n,
            "nameZh": zh,
            "location": {"lat": lat, "lon": lon},
            "districtId": d,
            "kind": kind,
        }
        for n, zh, lat, lon, d, kind in _GAZETTEER
    ]
    gaz_ts = (
        "/* AUTO-GENERATED by app.tools.export_demo_snapshot - do not edit. */\n"
        "export interface GazetteerPlace {\n"
        "  id: string; name: string; nameZh: string;\n"
        "  location: { lat: number; lon: number }; districtId: string; kind: string;\n"
        "}\n"
        "export const GAZETTEER: GazetteerPlace[] = "
        + json.dumps(places, separators=(",", ":"), ensure_ascii=False)
        + ";\n"
    )
    GAZETTEER_TS_OUT.write_text(gaz_ts, encoding="utf-8")
    print(f"wrote {GAZETTEER_TS_OUT.name} ({len(places)} places)")

    # District catalogue for the web UI: all districts generated by the
    # backend, with map framing derived from the real district bboxes so the
    # camera frames every area correctly (also used by place search → fly-to).
    import math  # noqa: PLC0415

    MERCATOR_EQ_M = 40_075_016.686  # equatorial circumference (Web Mercator)
    VIEWPORT_PX = 560  # approx side-panel era map viewport width
    districts = []
    for meta in DISTRICT_META:
        s, w, n, e = DISTRICT_BBOXES[meta["id"]]
        lat_mid = (s + n) / 2
        cos_lat = math.cos(math.radians(lat_mid))
        # Ground size of the wider bbox dimension, in metres.
        span_m = max((n - s) * MERCATOR_EQ_M / 360, (e - w) * MERCATOR_EQ_M / 360 * cos_lat)
        # Fit span into VIEWPORT_PX with padding: m/px = EQ*cos/(512*2^z).
        zoom = round(math.log2(VIEWPORT_PX * 0.9 * MERCATOR_EQ_M * cos_lat / (512 * span_m)), 1)
        districts.append(
            {
                **meta,
                "center": [(w + e) / 2, lat_mid],  # [lon, lat] for MapLibre
                "zoom": zoom,
            }
        )
    districts_ts = (
        "/* AUTO-GENERATED by app.tools.export_demo_snapshot - do not edit. */\n"
        "export interface CatalogueDistrict {\n"
        "  id: string; name: string; nameZh: string; kind: 'existing' | 'conceptual';\n"
        "  description: string; center: [number, number]; zoom: number;\n"
        "}\n"
        "export const DISTRICT_CATALOGUE: CatalogueDistrict[] = "
        + json.dumps(districts, separators=(",", ":"), ensure_ascii=False)
        + ";\n"
    )
    DISTRICTS_TS_OUT.write_text(districts_ts, encoding="utf-8")
    print(f"wrote {DISTRICTS_TS_OUT.name} ({len(districts)} districts)")


if __name__ == "__main__":
    main()
