"""Export a demo snapshot of the heat pipeline for the web app's offline mode.

Run:  python -m app.tools.export_demo_snapshot

Writes web/public/demo/*.json produced by the SAME HeatPredictionService that
powers the live API — a static render of the real pipeline (section 17 demo
resilience), never hand-authored values. The web app prefers the live API and
falls back to this snapshot, labelling it "OFFLINE SNAPSHOT".
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from app.config import REPO_ROOT
from app.core.types import HeatModelParameters
from app.engines.heat.engine import HeatPredictionService
from app.providers.cooling import CoolingSpotProvider
from app.providers.spatial import SpatialData
from app.providers.weather import MockWeatherProvider
from app.services.heatmap import HeatMapService

OUT_DIR = REPO_ROOT / "web" / "public" / "demo"
TS_OUT = REPO_ROOT / "web" / "src" / "features" / "heatmap" / "demoSnapshots.ts"
DISTRICTS = ["central-western", "kowloon-yau-tsim", "northern-metropolis"]
HOURS = [6, 9, 12, 15, 18, 21]
DATE = datetime(2026, 6, 21)  # fixed demo date (summer solstice)


def main() -> None:
    spatial = SpatialData()
    heat = HeatPredictionService(spatial, MockWeatherProvider(), HeatModelParameters())
    service = HeatMapService(spatial, heat)
    cooling = CoolingSpotProvider(spatial)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    snapshots: dict[str, object] = {}

    for district in DISTRICTS:
        for hour in HOURS:
            # subdivisions=2: 2x2 sub-cells per land-use cell (~75 m spacing)
            # so the web heatmap kernel merges into a CONTINUOUS field instead
            # of discrete per-cell blobs. Same HeatPredictionService per point.
            layer = service.build(
                district, datetime(DATE.year, DATE.month, DATE.day, hour),
                subdivisions=2,
            )
            snapshots[f"{district}|{hour}"] = layer
            path = OUT_DIR / f"heatmap_{district}_{hour:02d}.json"
            path.write_text(json.dumps(layer, separators=(",", ":")), encoding="utf-8")
            print(f"wrote {path.name}: {len(layer['cells'])} cells")

        spots = cooling.list(district)
        snapshots[f"{district}|cooling"] = spots
        spots_path = OUT_DIR / f"cooling_{district}.json"
        spots_path.write_text(
            json.dumps(spots, separators=(",", ":")),
            encoding="utf-8",
        )
        print(f"wrote {spots_path.name}")

    # Embedded snapshot module: lets the single-file build carry the whole
    # offline demo inside one HTML (no server, no fetches).
    ts = (
        "/* AUTO-GENERATED by app.tools.export_demo_snapshot - do not edit. */\n"
        "/* Static render of the real HeatPredictionService pipeline. */\n"
        "export const SNAPSHOTS: Record<string, unknown> = "
        + json.dumps(snapshots, separators=(",", ":"))
        + ";\n"
    )
    TS_OUT.write_text(ts, encoding="utf-8")
    print(f"wrote {TS_OUT.name} ({len(snapshots)} entries)")


if __name__ == "__main__":
    main()
